# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "tirlearner"
description: |
  Ensemble Method for TIR Transposable Element Annotation
keywords:
  - genomics
  - annotation
  - repeat
  - transposable
tools:
  - "TIR-Learner":
      description: TIR-Learner
      homepage: "https://github.com/lutianyu2001/TIR-Learner"
      documentation: "https://github.com/lutianyu2001/TIR-Learner"
      tool_dev_url: "https://github.com/lutianyu2001/TIR-Learner"
      doi: "10.1016/j.molp.2019.02.008"
      licence: ["GPLv3"]
      identifier: ""
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1' ]`
    - fasta:
        type: file
        description: Genome sequences in fasta format
        pattern: "*.{fsa,fa,fasta}"
  - - species:
        type: string
        description: |
          "maize", "rice" or "others"
output:
  - log:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1' ]`
      - ${prefix}.log:
          type: file
          description: Log from TIR-Learner
          pattern: "*.log"
  - fasta:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1' ]`
      - ${prefix}.fa:
          type: file
          description: Putative TIRs in fasta format
          pattern: "*.fa"
  - gff:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1' ]`
      - ${prefix}.gff3:
          type: file
          description: Putative TIRs in GFF3 format
          pattern: "*.gff3"
  - filtered_fasta:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1' ]`
      - ${prefix}.filtered.fa:
          type: file
          description: Filtered TIRs in fasta format
          pattern: "*.fa"
  - filtered_gff:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1' ]`
      - ${prefix}.filtered.gff3:
          type: file
          description: Filtered TIRs in GFF3 format
          pattern: "*.gff3"
  - versions:
      - versions.yml:
          type: file
          description: File containing software versions
          pattern: "versions.yml"
authors:
  - "@jguhlin"
  - "@GallVp"
maintainers:
  - "@jguhlin"
  - "@GallVp"
